version: '3'

services:
  mysqldb:
    image: mysql:5.7
    environment:
      MYSQL_USER: travis
      MYSQL_PASSWORD: Password12!
      MYSQL_ROOT_PASSWORD: Password12!
      MYSQL_DATABASE: testdb

  pgdb:
    image: postgres
    environment:
      # Lets use docker-entrypoint-initdb.d/init-user-db.sh
      # To set up user and Privileges
      # POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Password12!
      POSTGRES_DB: testdb

  rdata:
    container_name: rdata_container
    image: rdata_image
    command: bash -c "python --version"
    environment:
      # If IN_DOCKER is set, use service names as hosts(travis)
      # Otherwise use localhost (local tests)
      "IN_DOCKER" : "true"
    build: .
    depends_on:
      - mysqldb
      - pgdb
    ports:
      - 5001:80
